# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main
      - staging
      - develop
       - 'feature/*'  # Match all feature branches
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
    
      - name: Clean Install Test
        run: npm ci
        working-directory: ./application  # Adjust to your subdirectory path

      - name: Execute Unit Tests
        run: npm test
        working-directory: ./application  # Adjust to your subdirectory path

      ### Tests should go here 
      #
      #
      
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push' # Execute only on push to main branch
    steps:
      - name: Clean Install Test
        run: npm ci
        working-directory: ./application  # Adjust to your subdirectory path

      - name: Execute Unit Tests
        run: npm test
        working-directory: ./application  # Adjust to your subdirectory path

      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd ~/git/csc648-sp24-03-Team06/application
            git pull origin main
            npm ci
            pkill -9 node
            nohup npm start > /dev/null 2>&1 &
